import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import "@/styles/globals.css";
import MujeresMenu from "@/components/MujeresMenu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HombresLayout({ children }) {
  return (
    <article className={` text-white {inter.className}`}>
      <MujeresMenu />
      {children}
    </article>
  );
}
