import "@/styles/globals.css";
import MujeresMenu from "@/components/MujeresMenu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HombresLayout({ children }) {
  return (
    <article className={` text-white`}>
      <MujeresMenu />
      {children}
    </article>
  );
}
